debug mode for seeing individual geometries of the leaves.
tud-amr/fabrics pull request #78
Opened 2023-05-12 13:52 UTC by saraybakker1

2023-05-15 08:29 UTC, saraybakker1 commented on examples/panda_debug.py
> +    all_leaf_names = list(planner.leaves.keys())  #list of all possible leave names
fixed

2023-05-15 08:30 UTC, saraybakker1 commented on examples/panda_debug.py
> +
is it clear? :)

2023-05-15 11:50 UTC, maxspahn commented on examples/panda_debug.py
> +
yeah, looks good.

2023-05-16 09:44 UTC, maxspahn requested changes
It looks great, @saraybakker1 

However, this PR adds two relatively big example cases. I would prefer to have a smaller case to showcase how debugging works. I will add one for a point robot. In your specific use-case, you can then still use the debugging for the panda, but there are already so many examples in this folder.

I will do the changes now.

2023-05-16 10:05 UTC, saraybakker1 commented
Hi @maxspahn, that is also fine. If you would like, please add all examples (including the more complex ones) in the MultiFabrics git, then we can still use them

2023-05-17 07:30 UTC, maxspahn approved these changes

2023-05-17 07:31 UTC, merged